# This minimal base starts just from: kernel + systemd + rpm-ostree + bootloader.
# The intent of this is to inherit from this if you are doing something highly
# custom that e.g. might not involve Ignition or podman, but you do want
# rpm-ostree.
# We expect most people though using nestos-assembler to inherit from
# nestos-base.yaml.
packages:
 # Kernel + systemd.  Note we explicitly specify kernel-{core,modules}
 # because otherwise depsolving could bring in kernel-debug.
 - kernel  systemd
 # rpm-ostree
 - rpm-ostree nss-altfiles
 # firmware updates
 - fwupd

# bootloader
packages-aarch64:
  - grub2-efi-aa64 efibootmgr shim
packages-ppc64le:
  - grub2 ostree-grub2
packages-s390x:
  # On Fedora, this is provided by s390utils-core. on RHEL, this is for now
  # provided by s390utils-base, but soon will be -core too.
  - /usr/sbin/zipl
packages-x86_64:
  - grub2 grub2-efi-x64 efibootmgr shim
  - microcode_ctl
