ref: openEuler/${basearch}/nestos/stable
include: manifests/nestos.yaml

releasever: "LTS"

rojig:
  license: MIT
  name: nestos
  summary: NestOS stable

repos:
  - nestos

add-commit-metadata:
  fedora-coreos.stream: stable
